### ISSUE TITLE
Feature Request: Generate examples in documentation based on RAML inputs

### ISSUE THREAD

**Issue by ashishhk** [commercetools/rmf-codegen#162]
@davifantasia from documentation team requested to add generated examples in their documentations based on what they add as examples in RAML file.

Acceptance Criteria
 ?

**Comment by davifantasia** [comment]
### Acceptance Criteria

Examples should be included in the generated RAML doc for:

* properties of `uriParameters`
* properties of `queryParameters`
* body of a response

### Test API

If a test api is needed, we have one here - https://github.com/commercetools/commercetools-docs-kit/tree/master/websites/api-docs-smoke-test/source-raml/test

**Comment by jenschude** [comment]
Just released a new version with examples

**Comment by nkuehn** [comment]
@jenschude do you want me to open a separate issue for generating a simple curl call, too or do you consider that part of this one?

**Comment by jenschude** [comment]
Please open a new task. With description how it should look like :)

**Comment by ashishhk** [comment]
@nkuehn I am closing this topic for now, we can have another issues created for the generating a simple curl call.
