### ISSUE TITLE
Generate a cURL call example into the RamlDoc output for enpoints

### ISSUE THREAD

**Issue by nkuehn** [commercetools/rmf-codegen#169]
This refers to https://github.com/commercetools/commercetools-docs-kit/issues/445  - Please see the discussion there for all details.  

In addition to the structured example data implemented now (thanks!) it would be great to already get the generated code from the RAMLDoc instead of doing a part of code generation in the documentation stack and some somewhere else. 

To start with, a `curl` command suffices. 

### GET

```sh
curl  https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/customers?where=foo&limit=bar  -i \
     --header 'Authorization: Bearer YOUR_TOKEN' \
```

### POST
```sh
curl  https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/customers?param=foo  -i \
     --header 'Authorization: Bearer YOUR_TOKEN' \
     --header 'Content-Type: application/json' \
     --data '{ "name": "cool event" }' 
```
(if it's not a complex effort, pretty printing JSON into multiple lines could be useful e.g. if it exceeds 40 characters or something around that.  Can be a later improvement, too)

### DELETE

```sh
curl -X DELETE https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/customers/{id}  -i \
     --header 'Authorization: Bearer YOUR_TOKEN' \
```

## Proposed RAMLDoc output:

```yaml
# Resource
(resourceName): ByProjectKeyResourceArtificiallyComplexPathUriParameterOneByUriParameterOneByUriParameterTwo
(resourcePathUri): /{projectKey}/resource/artificially-complex/path/uri-parameter-one={uriParameterOne}/{uriParameterTwo}
uriParameters:
  ...
post:
  description: ...
  queryParameters:
    ...
  body:
    application/json:
      ...
  (codeExamples):
     curl: "curl  https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/resource/artificially-complex/path/uri-parameter-one={uriParameterOne}/{uriParameterTwo}  -i \\n  --header 'Authorization: Bearer YOUR_TOKEN' \\n  --header 'Content-Type: application/json' \\n  --data '{ \"foo\": \"bar\" }' "
  responses:
```
 * untested concerning string escapes.  choose whatever YAML String representation is easiest to generate here. 
  * "..." denotes omitted existing output

**Comment by jenschude** [comment]
https://github.com/jenschude/ramldoc/commit/21ca6059505c783c75e89b5cae1364b9b91ddfc0#diff-6730516e5c713b0a59da6c1058589da6R47-R65

https://github.com/jenschude/ramldoc/commit/21ca6059505c783c75e89b5cae1364b9b91ddfc0#diff-f4859c1e88d5cd5bd48a257c7fcc3088R60-R63

https://github.com/jenschude/ramldoc/commit/21ca6059505c783c75e89b5cae1364b9b91ddfc0#diff-119f3e647decbf09f2c1b813bab5fecdR38-R41
