### ISSUE TITLE
Empty `body` in generated RAML prevents docs website build

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/rmf-codegen#232]
`body` is sometimes empty in generated RAML. Eg. line 202 in /commercetools-docs/websites/api/src/api-specs/api/resources/ByProjectKeyCartDiscounts.raml and line 199 in /commercetools-docs/websites/api/src/api-specs/api/resources/ByProjectKeyApiClients.raml 

The empty `body` prevents generating the docs website. I receive a series of this error
<img width="570" alt="Screenshot 2021-06-15 at 11 30 21" src="https://user-images.githubusercontent.com/63338357/122029322-13da5e80-cdcd-11eb-8c47-e0412cd22ced.png">

**Comment by nkuehn** [comment]
Root cause lies in the affected Resources using a `baseResource` RAML specific inheritance feature.  The "type.baseResource" data of a Resource need to be flattened into the actual Endpoints like  `get.200...`

**Comment by jenschude** [comment]
The trait for the deprecation header always added a response with status code 200. And if the method didn't defined a body for this status code the body would have been empty. I splitted the deprecation trait for 200 and 201 and assigned them correctly

**Comment by nkuehn** [comment]
Thank you @jenschude!  Good to hear my first guess was really just a guess :-)
