### ISSUE TITLE
Fix: render "Postman" examples without name and as language "json"

### ISSUE THREAD

**Issue by nkuehn** [commercetools/rmf-codegen#235]
https://github.com/commercetools/rmf-codegen/blob/main/languages/ramldoc/src/main/kotlin/io/vrap/codegen/languages/ramldoc/model/RamlExampleRenderer.kt#L37 (TL;Dr: remove this line)

generates a name "postman" into the RAML_DOC if the example is from the `postman-example` annotation.  That does not make sense for the User in the docs UI.   For the user this is just an unnamed example. 

![image](https://user-images.githubusercontent.com/4006139/124229467-f36d0c80-db0d-11eb-8347-3d3404e64dd1.png)

**Comment by jenschude** [comment]
I released a v0.1.8 of the codegen. Now these examples are named postman only if there is no other example without a name defined.
