### ISSUE TITLE
Improve deprecation Marking

### ISSUE THREAD

**Issue by ashishhk** [commercetools/rmf-codegen#244]
Deprecated RAML specs should be reflected in generated SDKs including Models, Requests Builders., methods.

All SDKs are reflecting Deprecation annotations correctly at the end.
- [x] Java
- [x] Typescript
- [x] DotNet
- [x] PHP

e.g. check Import Sink - it should be completely deprecated.

**Comment by barbara79** [comment]
My analysis
************
until today we can find in our APIs:

**markDeprecated** annotation
- Property such as CustomerDraft and CustomerSignin
- Endpoint such as /import-sink and /categories/importSinkKey={importSinkKey}
- Class => no classes found

**deprecated** annotation
- Class such as PaymentSetAuthorizationActionBuilder and PaymentSetAuthorizationAction and PaymentSetAuthorizationActionImpl
- Property such as Payment
- Endpoint => no endpoint find

I'll add the result of my research for each language later

**Comment by barbara79** [comment]
Java:  
- MarkDeprecated is not working for:
     Endpoint deprecated is /importSinkKey={importSinkKey}
     ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyRequestBuilder is DEPRECATED
     
     NO Deprecation found for the rest of the uri /importSinkKey={importSinkKey}/import-operations :
     ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyPost
ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyImportOperationsByIdGet
	ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyImportOperationsByIdRequestBuilder
	ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyImportOperationsGet
	ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyImportOperationsRequestBuilder

- Deprecated: 
    - Class NOT removed:
           PaymentSetAuthorizationActionBuilder 
           PaymentSetAuthorizationAction 
           PaymentSetAuthorizationActionImpl.
     
Opened issue: https://github.com/commercetools/rmf-codegen/issues/270

**Comment by barbara79** [comment]
PHP:

- MarkDeprecated is not working for:
    - Property: NO annotation found in CustomerDraft, CustomerDraftBuilder, CustomerDraftModel for anonymousCartId
    - Endpoint: NO annotation found for the all endpoint deprecated    `/importSinkKey={importSinkKey}/import-operations`
    ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyImportOperationsByIdGet ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyImportOperationsGet ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyPost
    
 - Deprecated
     - Class deprecation: these classes are not removed
         PaymentSetAuthorizationAction 
         PaymentSetAuthorizationActionBuilder
          PaymentSetAuthorizationActionCollection 
          PaymentSetAuthorizationActionModel

**Comment by barbara79** [comment]
TYPESCRIPT:

- MarkDeprecated is not working for:

    -     Endpoint: NO annotation found for these classes
           ByProjectKeyImportSinksByImportSinkKeyRequestBuilder
          ByProjectKeyImportSinksRequestBuilder
          ByProjectKeyCategoriesImportSinkKeyByImportSinkKeyRequestBuilder
-  Deprecated
     - Property are not deprecated or removed
     - Classes are not deprecated or removed see PaymentSetAuthorizationAction
    
Opened issue: https://github.com/commercetools/rmf-codegen/issues/272

**Comment by barbara79** [comment]
DOTNET 

Opened issue: https://github.com/commercetools/rmf-codegen/issues/273
