### ISSUE TITLE
`./gradlew clean build  :tools:codegen-gradle-plugin:shadowJar` doesn't run

### ISSUE THREAD

**Issue by markus-azer** [commercetools/rmf-codegen#255]
after reading readme on how to build from here
https://github.com/commercetools/rmf-codegen/tree/main/tools/codegen-gradle-plugin#building
https://github.com/commercetools/rmf-codegen#build-the-fat-jar
i always get this error 
```
 problem was found with the configuration of task ':tools:cli-application:shadowJar' (type 'ShadowJar').|
 ```
 any tips how to solve it?

**Comment by jenschude** [comment]
Not yet. And yeah i saw it too
