### ISSUE TITLE
Watch mode does not work on M1 Macs

### ISSUE THREAD

**Issue by stmeissner** [commercetools/rmf-codegen#257]
Since I switched to an M1 Mac, the watch mode triggered with command line parameter `-w` does not work anymore. 

I've installed an ARM-64bit build of the Java 17 OpenJDK from [Azul](https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk) on my Mac running macOS Big Sur.

When I execute `rmf-codegen generate -w ...` following exception is thrown:

> io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

I am assuming the JDK I'm using is closer to Android than to Java Desktop and so this applies (from the link above):
> On desktop Java, this latter handler does nothing on an ExecutorService backed Scheduler and the application can keep running. However, Android is more strict and terminates the application in such uncaught exception cases.

Would be nice the watcher mode could also be supported for ARM-powered machines.

**Comment by jenschude** [comment]
Updated the directory watcher library which now references an Apple Silicon compatible JNA version
