### ISSUE TITLE
Display HTTP headers inside cURL examples

### ISSUE THREAD

**Issue by mar-gil** [commercetools/rmf-codegen#294]
Currently, the cURL request examples do not display the required headers if they are different from Authorization and Content-Type.

I provide below an example from the commercetools Frontend API. However, it would be useful to develop a "flexible" feature that would allow us to display any header we need in the future.

## Example from Frontend API

The following are the headers that should be displayed:

- [Accept: defined as trait](https://github.com/commercetools/commercetools-api-reference/blob/main/api-specs/frontend-api/api.raml#L41)
- [Frontastic-Locale: defined as trait](https://github.com/commercetools/commercetools-api-reference/blob/main/api-specs/frontend-api/api.raml#L50)
- [Frontastic-Path: used for the `GET` method in the `/page` endpoint](https://github.com/commercetools/commercetools-api-reference/blob/main/api-specs/frontend-api/resources/FrontasticPage.raml#L6)

**Example image** 

The cURL example is missing all three required headers (`Accept`, `Frontastic-Locale`, `Frontastic-Path`).

![image](https://user-images.githubusercontent.com/63046911/204232852-5bc0a4a7-5e74-4c81-b7db-0e930a13e66e.png)

**Comment by jenschude** [comment]
Fixed with 0.1.37
NPM version: 13.22.0

**Comment by jenschude** [comment]
Just saw that the headers are not only missing in the example

**Comment by jenschude** [comment]
released version: 0.1.38
NPM version: 13.23.0
